In [1]:
import numpy as np
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
from src.forecasting.informer.data.dataset import WorkloadPredictionDataset

train_dataset = WorkloadPredictionDataset(
    n_nodes=78,
    d_embed=172,
    is_train=True,
    train_start_minute=0,
    train_end_minute=14400,
    valid_start_minute=14400,
    valid_end_minute=20160,
    seq_len=12,
    label_len=6,
    pred_len=3,
    use_temporal_embedding=True
)

In [10]:
for batch in train_dataset:
    batch_x, batch_y, batch_x_mark, batch_y_mark = batch
    print(batch_x)
    break

[[   0.   18. 3743. ...    0.    0.    0.]
 [   0.   38. 2868. ...    0.    0.    0.]
 [   0.   10. 3007. ...    0.    0.    0.]
 ...
 [   0.   21. 3212. ...    0.    0.    0.]
 [   0.   19. 3986. ...    0.    0.    0.]
 [   0.   26. 3394. ...    0.    0.    0.]]


In [4]:
train_dataset.data.shape, train_dataset.labels.shape

((14400, 13494), (14400, 78))

In [5]:
valid_dataset = WorkloadPredictionDataset(
    n_nodes=78,
    d_embed=172,
    is_train=False,
    train_start_minute=0,
    train_end_minute=14400,
    valid_start_minute=14400,
    valid_end_minute=20160,
    seq_len=12,
    label_len=6,
    pred_len=3,
    use_temporal_embedding=True
)

In [6]:
train_dataset_without_embedding = WorkloadPredictionDataset(
    n_nodes=78,
    d_embed=172,
    is_train=True,
    train_start_minute=0,
    train_end_minute=14400,
    valid_start_minute=14400,
    valid_end_minute=20160,
    seq_len=12,
    label_len=6,
    pred_len=3,
    use_temporal_embedding=False
)

In [7]:
train_dataset_without_embedding.data.shape, train_dataset_without_embedding.labels.shape

((14400, 78), (14400, 78))

In [8]:
train_dataset_with_node = WorkloadPredictionDataset(
    n_nodes=78,
    d_embed=172,
    is_train=True,
    train_start_minute=0,
    train_end_minute=14400,
    valid_start_minute=14400,
    valid_end_minute=20160,
    seq_len=12,
    label_len=6,
    pred_len=3,
    use_temporal_embedding=True,
    node_id=8
)

In [9]:
train_dataset_with_node.data.shape, train_dataset_with_node.labels.shape

((14400, 173), (14400, 1))